import type { Product } from './types'

export const products: Product[] = [
  { id:'p1', name:'Essential Hoodie', category:'Hoodies', price:69, description:'Heavyweight relaxed-fit hoodie with a clean YAROPLUGG attitude.', composition:'80% cotton, 20% polyester', sizes:['S','M','L','XL'], colors:[{name:'Black',hex:'#0b0b0b'},{name:'Cream',hex:'#e9e2d6'}], images:['https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85'], featured:true },
  { id:'p2', name:'Heavy Basic Tee', category:'T-Shirts', price:39, description:'Dense cotton tee with a straight silhouette and premium everyday feel.', composition:'100% cotton', sizes:['S','M','L','XL'], colors:[{name:'White',hex:'#f4f4f2'},{name:'Black',hex:'#0b0b0b'}], images:['https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=900&q=85'], featured:true },
  { id:'p3', name:'Relaxed Cargo', category:'Pants', price:79, description:'Relaxed cargo trousers with adjustable hems and utility pockets.', composition:'98% cotton, 2% elastane', sizes:['S','M','L'], colors:[{name:'Olive',hex:'#4c5141'},{name:'Black',hex:'#0b0b0b'}], images:['https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=900&q=85'] },
  { id:'p4', name:'Daily Bomber', category:'Jackets', price:99, description:'Lightweight everyday bomber with minimal hardware and a clean fit.', composition:'100% polyester', sizes:['M','L','XL'], colors:[{name:'Black',hex:'#0b0b0b'}], images:['https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=900&q=85'] },
  { id:'p5', name:'Soft Logo Tee', category:'T-Shirts', price:35, description:'Soft cotton tee with a subtle embroidered YAROPLUGG mark.', composition:'100% cotton', sizes:['S','M','L'], colors:[{name:'Grey',hex:'#8f8f8b'},{name:'White',hex:'#f4f4f2'}], images:['https://images.unsplash.com/photo-1583743814966-8936f37f4a0e?auto=format&fit=crop&w=900&q=85'] },
  { id:'p6', name:'Wide Track Pants', category:'Pants', price:59, description:'Wide-leg track pants built for an easy streetwear silhouette.', composition:'65% cotton, 35% polyester', sizes:['S','M','L','XL'], colors:[{name:'Black',hex:'#0b0b0b'},{name:'Grey',hex:'#777772'}], images:['https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=900&q=85'] },
]
