import React,{useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Search,ShoppingBag,House,UserRound,ChevronLeft,Plus,Minus,X,SlidersHorizontal,Heart,PackageOpen,ChevronDown,ArrowUpRight} from 'lucide-react'
import './index.css'
import {products} from './data'
import type {Category,Product,CartItem} from './types'

type Screen='home'|'catalog'|'orders'|'profile'
type Order={id:string;createdAt:string;status:string;total:number;items:CartItem[]}
const cats:Category[]=['All','T-Shirts','Hoodies','Pants','Jackets']
const sizes=['S','M','L','XL']

function App(){
 const [screen,setScreen]=useState<Screen>('home'),[selected,setSelected]=useState<Product|null>(null),[cart,setCart]=useState<CartItem[]>([]),[query,setQuery]=useState(''),[cat,setCat]=useState<Category>('All'),[showFilters,setShowFilters]=useState(false),[filterSize,setFilterSize]=useState('All'),[filterColor,setFilterColor]=useState('All'),[maxPrice,setMaxPrice]=useState(100),[showCart,setShowCart]=useState(false),[showCheckout,setShowCheckout]=useState(false),[toast,setToast]=useState(''),[orders,setOrders]=useState<Order[]>([]),[favorites,setFavorites]=useState<string[]>([])
 const colors=useMemo(()=>['All',...Array.from(new Set(products.flatMap(p=>p.colors.map(c=>c.name))))],[products])
 const filtered=useMemo(()=>products.filter(p=>{const text=p.name.toLowerCase().includes(query.toLowerCase())||p.description.toLowerCase().includes(query.toLowerCase());const size=filterSize==='All'||p.sizes.includes(filterSize);const color=filterColor==='All'||p.colors.some(c=>c.name===filterColor);return(cat==='All'||p.category===cat)&&text&&size&&color&&p.price<=maxPrice}),[cat,query,filterSize,filterColor,maxPrice])
 const total=cart.reduce((s,i)=>s+i.product.price*i.quantity,0),count=cart.reduce((s,i)=>s+i.quantity,0)
 function add(item:CartItem){setCart(c=>{const x=c.find(i=>i.product.id===item.product.id&&i.size===item.size&&i.color===item.color);return x?c.map(i=>i===x?{...i,quantity:i.quantity+item.quantity}:i):[...c,item]});notify('Added to bag')}
 function notify(v:string){setToast(v);window.setTimeout(()=>setToast(''),1500)}
 function toggleFavorite(id:string){setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id])}
 function createOrder(customer:{name:string;phone:string;delivery:string}){const order={id:String(Date.now()).slice(-6),createdAt:new Date().toISOString(),status:'new',total,items:cart};setOrders(o=>[order,...o]);setCart([]);setShowCheckout(false);setScreen('orders');notify('Order placed')}
 return <div className="min-h-screen bg-[#080808] text-white"><main className="mx-auto max-w-md min-h-screen bg-[#080808] safe-bottom">
  <header className="sticky top-0 z-20 glass px-5 py-4 flex items-center justify-between border-b border-white/10"><button onClick={()=>setScreen('home')} className="text-left leading-none"><div className="text-[10px] uppercase tracking-[.34em] text-neutral-500">EST. 2026</div><div className="mt-1 text-[22px] font-black tracking-[-.06em]">YAROPLUGG</div></button><div className="flex items-center gap-2"><button onClick={()=>{setScreen('catalog');setTimeout(()=>document.getElementById('search')?.focus(),50)}} className="rounded-full border border-white/10 p-3 text-neutral-300 tap"><Search size={18}/></button><button onClick={()=>setShowCart(true)} className="relative rounded-full bg-white text-black p-3 tap"><ShoppingBag size={18}/>{count>0&&<span className="absolute -right-1 -top-1 bg-[#ff2d2d] text-white text-[10px] font-bold w-5 h-5 rounded-full flex items-center justify-center">{count}</span>}</button></div></header>
  {screen==='home'&&<Home onCatalog={()=>setScreen('catalog')} onProduct={setSelected} favorites={favorites} onFavorite={toggleFavorite}/>} 
  {screen==='catalog'&&<Catalog query={query} setQuery={setQuery} cat={cat} setCat={setCat} products={filtered} onProduct={setSelected} onFilters={()=>setShowFilters(true)} favorites={favorites} onFavorite={toggleFavorite}/>} 
  {screen==='orders'&&<Orders orders={orders}/>} {screen==='profile'&&<Profile/>}
  <nav className="fixed bottom-0 left-0 right-0 z-30 mx-auto max-w-md border-t border-white/10 glass px-4 py-3 flex justify-around pb-[calc(12px+env(safe-area-inset-bottom))]"><Nav icon={<House size={18}/>} label="SHOP" active={screen==='home'} onClick={()=>setScreen('home')}/><Nav icon={<Search size={18}/>} label="CATEGORIES" active={screen==='catalog'} onClick={()=>setScreen('catalog')}/><Nav icon={<Heart size={18}/>} label="FAVORITES" active={false} onClick={()=>{setScreen('catalog');setQuery('')}}/><Nav icon={<UserRound size={18}/>} label="PROFILE" active={screen==='profile'} onClick={()=>setScreen('profile')}/></nav>
  {selected&&<ProductModal product={selected} onClose={()=>setSelected(null)} onAdd={add}/>} {showCart&&<Cart items={cart} total={total} onClose={()=>setShowCart(false)} onChange={setCart} onCheckout={()=>{setShowCart(false);setShowCheckout(true)}}/>} {showCheckout&&<Checkout total={total} onClose={()=>setShowCheckout(false)} onDone={createOrder}/>} {showFilters&&<Filters size={filterSize} color={filterColor} maxPrice={maxPrice} colors={colors} onClose={()=>setShowFilters(false)} onApply={(s,c,p)=>{setFilterSize(s);setFilterColor(c);setMaxPrice(p);setShowFilters(false)}}/>} {toast&&<div className="fixed bottom-24 left-1/2 -translate-x-1/2 z-50 bg-white text-black rounded-full px-5 py-3 text-sm font-semibold shadow-xl">{toast}</div>}
 </main></div>
}
function Nav({icon,label,active,onClick}:{icon:React.ReactNode;label:string;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`flex flex-col items-center gap-1 text-[9px] tracking-[.16em] ${active?'text-white':'text-neutral-500'}`}>{icon}<span>{label}</span></button>}
function Home({onCatalog,onProduct,favorites,onFavorite}:{onCatalog:()=>void;onProduct:(p:Product)=>void;favorites:string[];onFavorite:(id:string)=>void}){return <div className="px-5 pt-6"><section className="rounded-[30px] bg-white text-black p-6 min-h-[340px] flex flex-col justify-between overflow-hidden relative"><div className="relative z-10"><div className="flex items-center justify-between"><p className="text-[10px] uppercase tracking-[.28em] text-neutral-500">NEW COLLECTION / 01</p><span className="text-[#ff2d2d] text-xs font-black">YPG</span></div><h1 className="mt-10 text-[54px] font-black tracking-[-.07em] leading-[.88]">WEAR<br/>LESS.<br/><span className="text-neutral-400">CHOOSE<br/>BETTER.</span></h1></div><button onClick={onCatalog} className="relative z-10 w-fit bg-black text-white rounded-full px-6 py-3.5 text-sm font-bold flex items-center gap-2 tap">SHOP COLLECTION <ArrowUpRight size={16}/></button><div className="absolute -right-24 -bottom-24 w-80 h-80 rounded-full border-[52px] border-neutral-200"/></section><div className="flex gap-5 mt-8 mb-5 overflow-x-auto scrollbar-hide border-b border-white/10">{cats.slice(1,4).map(c=><button key={c} onClick={()=>{onCatalog()}} className="pb-3 text-[11px] tracking-[.2em] font-semibold whitespace-nowrap text-neutral-400">{c.toUpperCase()}</button>)}</div><div className="flex items-end justify-between mb-4"><div><p className="text-[10px] tracking-[.25em] text-[#ff2d2d]">SELECTED</p><h2 className="mt-1 text-2xl font-bold tracking-tight">NEW IN</h2></div><button onClick={onCatalog} className="text-xs text-neutral-400 flex items-center gap-1">VIEW ALL <ArrowUpRight size={14}/></button></div><div className="grid grid-cols-2 gap-x-3 gap-y-7">{products.filter(p=>p.featured).map(p=><ProductCard key={p.id} p={p} onClick={()=>onProduct(p)} favorite={favorites.includes(p.id)} onFavorite={()=>onFavorite(p.id)}/>)}</div></div>}
function Catalog({query,setQuery,cat,setCat,products,onProduct,onFilters,favorites,onFavorite}:{query:string;setQuery:(v:string)=>void;cat:Category;setCat:(v:Category)=>void;products:Product[];onProduct:(p:Product)=>void;onFilters:()=>void;favorites:string[];onFavorite:(id:string)=>void}){return <div className="px-5 pt-6"><div className="flex items-end justify-between"><div><p className="text-[10px] tracking-[.25em] text-[#ff2d2d]">COLLECTION</p><h1 className="text-3xl font-black tracking-tight mt-1">SHOP ALL</h1></div><button onClick={onFilters} className="rounded-full border border-white/10 p-3 text-neutral-300"><SlidersHorizontal size={17}/></button></div><div className="mt-5 relative"><Search className="absolute left-4 top-1/2 -translate-y-1/2 text-neutral-500" size={17}/><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="SEARCH PRODUCTS" className="w-full rounded-full bg-white/5 border border-white/10 pl-11 pr-4 py-3.5 text-xs tracking-[.12em] text-white outline-none focus:border-white/30"/></div><div className="flex gap-5 overflow-x-auto scrollbar-hide py-5 border-b border-white/10">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={`whitespace-nowrap pb-2 text-[11px] tracking-[.18em] font-semibold border-b ${cat===c?'text-white border-[#ff2d2d]':'text-neutral-500 border-transparent'}`}>{c.toUpperCase()}</button>)}</div><div className="py-4 flex justify-between text-[10px] tracking-[.18em] text-neutral-500"><span>{products.length} PRODUCTS</span><span>€20 — €100</span></div><div className="grid grid-cols-2 gap-x-3 gap-y-7">{products.map(p=><ProductCard key={p.id} p={p} onClick={()=>onProduct(p)} favorite={favorites.includes(p.id)} onFavorite={()=>onFavorite(p.id)}/>)}</div>{products.length===0&&<div className="py-20 text-center text-neutral-500 text-sm">NO PRODUCTS FOUND</div>}</div>}
function ProductCard({p,onClick,favorite,onFavorite}:{p:Product;onClick:()=>void;favorite:boolean;onFavorite:()=>void}){return <div className="text-left group product-card"><div className="relative aspect-[.76] rounded-[22px] overflow-hidden bg-neutral-900"><button onClick={onClick} className="absolute inset-0 z-0"><img src={p.images[0]} alt={p.name} className="w-full h-full object-cover product-image"/></button><button onClick={onFavorite} className="absolute right-3 top-3 z-10 rounded-full bg-black/55 backdrop-blur p-2 text-white" aria-label="Favorite"><Heart size={15} fill={favorite?'currentColor':'none'} className={favorite?'text-[#ff2d2d]':''}/></button><span className="absolute left-3 bottom-3 z-10 bg-white text-black rounded-full px-2.5 py-1 text-[9px] tracking-[.14em] font-bold">{p.category.toUpperCase()}</span></div><button onClick={onClick} className="w-full text-left pt-3 px-1"><div className="flex justify-between gap-2"><div className="text-sm font-semibold text-white">{p.name}</div><div className="text-sm text-neutral-300">€{p.price}</div></div><div className="mt-1 text-[10px] tracking-[.14em] text-neutral-600">YAROPLUGG / ESSENTIALS</div></button></div>}
function ProductModal({product,onClose,onAdd}:{product:Product;onClose:()=>void;onAdd:(x:CartItem)=>void}){const[size,setSize]=useState(product.sizes[1]||product.sizes[0]),[color,setColor]=useState(product.colors[0].name);return <div className="fixed inset-0 z-40 bg-black/80 flex items-end"><div className="bg-[#0d0d0d] border-t border-white/10 w-full max-w-md mx-auto rounded-t-[30px] max-h-[92vh] overflow-y-auto"><div className="relative"><img src={product.images[0]} alt={product.name} className="w-full aspect-[.9] object-cover"/><button onClick={onClose} className="absolute right-4 top-4 bg-white text-black rounded-full p-2"><X size={19}/></button></div><div className="p-5"><div className="flex justify-between gap-4"><div><div className="text-[10px] uppercase tracking-[.22em] text-[#ff2d2d]">{product.category}</div><h2 className="text-2xl font-bold mt-1">{product.name}</h2></div><div className="text-xl font-semibold">€{product.price}</div></div><p className="mt-4 text-sm text-neutral-400 leading-6">{product.description}</p><div className="mt-5"><div className="text-[11px] tracking-[.16em] text-neutral-500 mb-2">SIZE</div><div className="flex gap-2">{product.sizes.map(s=><button key={s} onClick={()=>setSize(s)} className={`w-11 h-11 rounded-xl border text-sm ${size===s?'bg-white text-black border-white':'bg-white/5 border-white/10 text-white'}`}>{s}</button>)}</div></div><div className="mt-5"><div className="text-[11px] tracking-[.16em] text-neutral-500 mb-2">COLOR · {color.toUpperCase()}</div><div className="flex gap-3">{product.colors.map(c=><button key={c.name} aria-label={c.name} onClick={()=>setColor(c.name)} style={{background:c.hex}} className={`w-9 h-9 rounded-full border-2 ${color===c.name?'border-white ring-2 ring-[#ff2d2d] ring-offset-2 ring-offset-[#0d0d0d]':'border-white/20'}`}/>)}</div></div><div className="mt-5 text-xs text-neutral-500">COMPOSITION: {product.composition}</div><button onClick={()=>{onAdd({product,size,color,quantity:1});onClose()}} className="mt-6 w-full bg-[#ff2d2d] text-white rounded-2xl py-4 font-bold tap">ADD TO BAG · €{product.price}</button></div></div></div>}
function Cart({items,total,onClose,onChange,onCheckout}:{items:CartItem[];total:number;onClose:()=>void;onChange:(x:CartItem[])=>void;onCheckout:()=>void}){return <div className="fixed inset-0 z-40 bg-black/80 flex items-end"><div className="bg-[#0d0d0d] border-t border-white/10 w-full max-w-md mx-auto rounded-t-[30px] p-5 max-h-[88vh] overflow-y-auto"><div className="flex justify-between items-center"><h2 className="text-2xl font-bold">BAG</h2><button onClick={onClose} className="rounded-full bg-white text-black p-2"><X size={18}/></button></div>{items.length===0?<div className="py-20 text-center"><ShoppingBag className="mx-auto text-neutral-600" size={48}/><p className="mt-4 font-semibold">YOUR BAG IS EMPTY</p><p className="text-sm text-neutral-500 mt-1">Add something from the collection.</p></div>:<>{items.map((i,idx)=><div key={`${i.product.id}-${i.size}-${i.color}`} className="flex gap-3 py-4 border-b border-white/10"><img src={i.product.images[0]} alt="" className="w-20 h-24 rounded-xl object-cover"/><div className="flex-1"><div className="font-medium">{i.product.name}</div><div className="text-xs text-neutral-500 mt-1">{i.color} · {i.size}</div><div className="flex items-center justify-between mt-4"><div className="flex items-center gap-2 bg-white/5 rounded-full p-1"><button onClick={()=>onChange(items.map((x,j)=>j===idx?{...x,quantity:Math.max(1,x.quantity-1)}:x))} className="p-1"><Minus size={14}/></button><span className="text-sm w-5 text-center">{i.quantity}</span><button onClick={()=>onChange(items.map((x,j)=>j===idx?{...x,quantity:x.quantity+1}:x))} className="p-1"><Plus size={14}/></button></div><b>€{i.product.price*i.quantity}</b></div></div></div>)}<div className="flex justify-between text-lg font-semibold pt-5"><span>TOTAL</span><span>€{total}</span></div><button onClick={onCheckout} className="mt-4 w-full bg-[#ff2d2d] text-white rounded-2xl py-4 font-bold">CHECKOUT</button></>}</div></div>}
function Checkout({total,onClose,onDone}:{total:number;onClose:()=>void;onDone:(x:{name:string;phone:string;delivery:string})=>void}){const[name,setName]=useState(''),[phone,setPhone]=useState(''),[delivery,setDelivery]=useState('SmartPost / Omniva');return <div className="fixed inset-0 z-50 bg-[#080808] overflow-y-auto"><div className="mx-auto max-w-md p-5 min-h-screen"><button onClick={onClose} className="rounded-full border border-white/10 p-2"><ChevronLeft/></button><p className="mt-8 text-[10px] tracking-[.25em] text-[#ff2d2d]">ORDER</p><h1 className="text-3xl font-black mt-1">CHECKOUT</h1><div className="mt-7 space-y-4"><Field label="NAME" value={name} onChange={setName} placeholder="Your name"/><Field label="PHONE" value={phone} onChange={setPhone} placeholder="+372 ..."/><div><label className="text-[10px] tracking-[.16em] text-neutral-500">DELIVERY</label><select value={delivery} onChange={e=>setDelivery(e.target.value)} className="mt-2 w-full bg-white/5 border border-white/10 rounded-2xl p-4 text-white"><option className="bg-black">SmartPost / Omniva</option><option className="bg-black">Courier</option><option className="bg-black">Pickup</option></select></div><div><label className="text-[10px] tracking-[.16em] text-neutral-500">PAYMENT</label><div className="mt-2 rounded-2xl bg-white/5 border border-white/10 p-4">Cash on delivery</div></div></div><div className="mt-8 rounded-2xl bg-white text-black p-4 flex justify-between"><span>ORDER TOTAL</span><b>€{total}</b></div><button disabled={!name||phone.replace(/\D/g,'').length<7} onClick={()=>onDone({name,phone,delivery})} className="mt-4 w-full bg-[#ff2d2d] disabled:bg-neutral-700 text-white rounded-2xl py-4 font-bold">PLACE ORDER</button></div></div>}
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(x:string)=>void;placeholder:string}){return <div><label className="text-[10px] tracking-[.16em] text-neutral-500">{label}</label><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="mt-2 w-full bg-white/5 border border-white/10 rounded-2xl p-4 text-white outline-none focus:border-white/30"/></div>}
function Filters({size,color,maxPrice,colors,onClose,onApply}:{size:string;color:string;maxPrice:number;colors:string[];onClose:()=>void;onApply:(s:string,c:string,p:number)=>void}){const[s,setS]=useState(size),[c,setC]=useState(color),[p,setP]=useState(maxPrice);return <div className="fixed inset-0 z-50 bg-black/80 flex items-end"><div className="bg-[#0d0d0d] border-t border-white/10 w-full max-w-md mx-auto rounded-t-[30px] p-5"><div className="flex items-center justify-between"><h2 className="text-2xl font-bold">FILTERS</h2><button onClick={onClose} className="rounded-full bg-white text-black p-2"><X size={18}/></button></div><div className="mt-6"><div className="text-[10px] tracking-[.16em] text-neutral-500 mb-2">SIZE</div><div className="flex gap-2 flex-wrap">{['All',...sizes].map(x=><button key={x} onClick={()=>setS(x)} className={`px-4 py-2 rounded-full text-sm ${s===x?'bg-white text-black':'bg-white/5 border border-white/10'}`}>{x}</button>)}</div></div><div className="mt-6"><div className="text-[10px] tracking-[.16em] text-neutral-500 mb-2">COLOR</div><div className="relative"><select value={c} onChange={e=>setC(e.target.value)} className="w-full bg-white/5 border border-white/10 rounded-2xl p-4 text-white appearance-none">{colors.map(x=><option className="bg-black" key={x}>{x}</option>)}</select><ChevronDown className="absolute right-4 top-4 pointer-events-none text-neutral-400" size={18}/></div></div><div className="mt-6"><div className="flex justify-between text-[10px] tracking-[.16em] text-neutral-500"><span>MAXIMUM PRICE</span><span>€{p}</span></div><input type="range" min="20" max="100" value={p} onChange={e=>setP(Number(e.target.value))} className="w-full mt-3"/></div><button onClick={()=>onApply(s,c,p)} className="mt-7 w-full bg-[#ff2d2d] text-white rounded-2xl py-4 font-bold">APPLY FILTERS</button></div></div>}
function Orders({orders}:{orders:Order[]}){return <div className="px-5 pt-7"><p className="text-[10px] tracking-[.25em] text-[#ff2d2d]">ACCOUNT</p><h1 className="text-3xl font-black mt-1">ORDERS</h1>{orders.length===0?<div className="mt-8 rounded-3xl bg-white/5 border border-white/10 p-8 text-center"><PackageOpen className="mx-auto text-neutral-500" size={34}/><h2 className="mt-4 font-semibold">NO ORDERS YET</h2><p className="mt-2 text-sm text-neutral-500">Your order status will appear here after checkout.</p></div>:<div className="mt-5 space-y-3">{orders.map(o=><div key={o.id} className="rounded-3xl bg-white/5 border border-white/10 p-5"><div className="flex justify-between"><b>ORDER #{o.id}</b><span className="text-[9px] tracking-[.14em] rounded-full bg-[#ff2d2d] px-3 py-1">NEW</span></div><div className="mt-3 text-sm text-neutral-500">{o.items.length} items · €{o.total}</div></div>)}</div>}</div>}
function Profile(){return <div className="px-5 pt-7"><p className="text-[10px] tracking-[.25em] text-[#ff2d2d]">YAROPLUGG</p><h1 className="text-3xl font-black mt-1">PROFILE</h1><div className="mt-6 rounded-3xl bg-white text-black p-6"><div className="text-[10px] tracking-[.2em] text-neutral-500">TELEGRAM</div><div className="text-xl font-bold mt-2">Your account</div><p className="text-sm text-neutral-500 mt-3">Your profile data will be provided by Telegram.</p></div><div className="mt-3 bg-white/5 border border-white/10 rounded-2xl p-4">Store support</div></div>}
createRoot(document.getElementById('root')!).render(<App/>)
