import React,{useEffect,useMemo,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {Search,ShoppingBag,House,UserRound,Plus,Minus,X,SlidersHorizontal,Heart,PackageOpen,ChevronDown,ArrowUpRight,ChevronLeft} from 'lucide-react'
import './index.css'
import {products} from './data'
import type {Category,Product,CartItem} from './types'

type Screen='home'|'catalog'|'orders'|'profile'
type Order={id:string;createdAt:string;status:string;total:number;items:CartItem[]}
const cats:Category[]=['All','T-Shirts','Hoodies','Pants','Jackets']
const sizes=['S','M','L','XL']

function readStorage<T>(key:string,fallback:T):T{try{const raw=localStorage.getItem(key);return raw?JSON.parse(raw):fallback}catch{return fallback}}
function App(){
 const [screen,setScreen]=useState<Screen>('home')
 const [selected,setSelected]=useState<Product|null>(null)
 const [cart,setCart]=useState<CartItem[]>(()=>readStorage('yp-cart',[]))
 const [query,setQuery]=useState('')
 const [cat,setCat]=useState<Category>('All')
 const [showFilters,setShowFilters]=useState(false)
 const [filterSize,setFilterSize]=useState('All')
 const [filterColor,setFilterColor]=useState('All')
 const [maxPrice,setMaxPrice]=useState(100)
 const [showCart,setShowCart]=useState(false)
 const [showCheckout,setShowCheckout]=useState(false)
 const [toast,setToast]=useState('')
 const [orders,setOrders]=useState<Order[]>(()=>readStorage('yp-orders',[]))
 const [favorites,setFavorites]=useState<string[]>(()=>readStorage('yp-favorites',[]))
 const colors=useMemo(()=>['All',...Array.from(new Set(products.flatMap(p=>p.colors.map(c=>c.name))))],[])
 const filtered=useMemo(()=>products.filter(p=>{const text=p.name.toLowerCase().includes(query.toLowerCase())||p.description.toLowerCase().includes(query.toLowerCase());const size=filterSize==='All'||p.sizes.includes(filterSize);const color=filterColor==='All'||p.colors.some(c=>c.name===filterColor);return(cat==='All'||p.category===cat)&&text&&size&&color&&p.price<=maxPrice}),[cat,query,filterSize,filterColor,maxPrice])
 const total=cart.reduce((s,i)=>s+i.product.price*i.quantity,0),count=cart.reduce((s,i)=>s+i.quantity,0)
 useEffect(()=>{localStorage.setItem('yp-cart',JSON.stringify(cart))},[cart])
 useEffect(()=>{localStorage.setItem('yp-orders',JSON.stringify(orders))},[orders])
 useEffect(()=>{localStorage.setItem('yp-favorites',JSON.stringify(favorites))},[favorites])
 useEffect(()=>{const tg=(window as any).Telegram?.WebApp;if(tg){tg.ready();tg.expand()}},[])
 function add(item:CartItem){setCart(c=>{const x=c.find(i=>i.product.id===item.product.id&&i.size===item.size&&i.color===item.color);return x?c.map(i=>i===x?{...i,quantity:i.quantity+item.quantity}:i):[...c,item]});notify('Added to bag')}
 function notify(v:string){setToast(v);window.setTimeout(()=>setToast(''),1500)}
 function toggleFavorite(id:string){setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id])}
 function createOrder(customer:{name:string;phone:string;delivery:string}){const order={id:String(Date.now()).slice(-6),createdAt:new Date().toISOString(),status:'new',total,items:cart};setOrders(o=>[order,...o]);setCart([]);setShowCheckout(false);setScreen('orders');notify('Order placed')}
 function openCategory(c:Category){setCat(c);setScreen('catalog');window.scrollTo({top:0,behavior:'smooth'})}
 return <div className="app-shell"><main className="store-shell safe-bottom">
  <header className="site-header"><button onClick={()=>setScreen('home')} className="brand-button" aria-label="YAROPLUGG home"><img src="/logo.png" alt="YAROPLUGG" className="brand-logo"/></button><div className="header-actions"><button onClick={()=>{setScreen('catalog');setTimeout(()=>document.getElementById('search')?.focus(),50)}} className="icon-button" aria-label="Search"><Search size={18}/></button><button onClick={()=>setShowCart(true)} className="bag-button" aria-label="Bag"><ShoppingBag size={18}/>{count>0&&<span className="bag-count">{count}</span>}</button></div></header>
  {screen==='home'&&<Home onCatalog={()=>setScreen('catalog')} onCategory={openCategory} onProduct={setSelected} favorites={favorites} onFavorite={toggleFavorite}/>} 
  {screen==='catalog'&&<Catalog query={query} setQuery={setQuery} cat={cat} setCat={setCat} products={filtered} onProduct={setSelected} onFilters={()=>setShowFilters(true)} favorites={favorites} onFavorite={toggleFavorite}/>} 
  {screen==='orders'&&<Orders orders={orders}/>} {screen==='profile'&&<Profile/>}
  <nav className="bottom-nav" aria-label="Main navigation"><Nav icon={<House size={17}/>} label="SHOP" active={screen==='home'} onClick={()=>setScreen('home')}/><Nav icon={<Search size={17}/>} label="CATEGORIES" active={screen==='catalog'} onClick={()=>setScreen('catalog')}/><Nav icon={<Heart size={17}/>} label="FAVORITES" active={false} onClick={()=>{setScreen('catalog');setQuery('');setCat('All')}}/><Nav icon={<UserRound size={17}/>} label="PROFILE" active={screen==='profile'} onClick={()=>setScreen('profile')}/></nav>
  {selected&&<ProductModal product={selected} onClose={()=>setSelected(null)} onAdd={add}/>} {showCart&&<Cart items={cart} total={total} onClose={()=>setShowCart(false)} onChange={setCart} onCheckout={()=>{setShowCart(false);setShowCheckout(true)}}/>} {showCheckout&&<Checkout total={total} onClose={()=>setShowCheckout(false)} onDone={createOrder}/>} {showFilters&&<Filters size={filterSize} color={filterColor} maxPrice={maxPrice} colors={colors} onClose={()=>setShowFilters(false)} onApply={(s,c,p)=>{setFilterSize(s);setFilterColor(c);setMaxPrice(p);setShowFilters(false)}}/>} {toast&&<div className="toast">{toast}</div>}
 </main></div>
}
function Nav({icon,label,active,onClick}:{icon:React.ReactNode;label:string;active:boolean;onClick:()=>void}){return <button onClick={onClick} className={`nav-item ${active?'is-active':''}`}><span className="nav-icon">{icon}</span><span>{label}</span></button>}
function Home({onCatalog,onCategory,onProduct,favorites,onFavorite}:{onCatalog:()=>void;onCategory:(c:Category)=>void;onProduct:(p:Product)=>void;favorites:string[];onFavorite:(id:string)=>void}){return <div className="page-pad"><section className="hero-card"><div className="hero-top"><p>NEW COLLECTION / 01</p><span>YPG</span></div><h1>WEAR<br/>LESS.<br/><em>CHOOSE<br/>BETTER.</em></h1><button onClick={onCatalog} className="primary-dark">SHOP COLLECTION <ArrowUpRight size={16}/></button><div className="hero-ring"/></section><div className="category-strip">{cats.slice(1,4).map(c=><button key={c} onClick={()=>onCategory(c)}>{c.toUpperCase()}</button>)}</div><div className="section-head"><div><p>SELECTED</p><h2>NEW IN</h2></div><button onClick={onCatalog}>VIEW ALL <ArrowUpRight size={14}/></button></div><div className="product-grid">{products.filter(p=>p.featured).map(p=><ProductCard key={p.id} p={p} onClick={()=>onProduct(p)} favorite={favorites.includes(p.id)} onFavorite={()=>onFavorite(p.id)}/>)}</div></div>}
function Catalog({query,setQuery,cat,setCat,products,onProduct,onFilters,favorites,onFavorite}:{query:string;setQuery:(v:string)=>void;cat:Category;setCat:(v:Category)=>void;products:Product[];onProduct:(p:Product)=>void;onFilters:()=>void;favorites:string[];onFavorite:(id:string)=>void}){return <div className="page-pad"><div className="catalog-head"><div><p>COLLECTION</p><h1>SHOP ALL</h1></div><button onClick={onFilters} className="filter-button" aria-label="Filters"><SlidersHorizontal size={17}/></button></div><div className="search-box"><Search size={17}/><input id="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="SEARCH PRODUCTS"/></div><div className="category-strip catalog-tabs">{cats.map(c=><button key={c} onClick={()=>setCat(c)} className={cat===c?'active':''}>{c.toUpperCase()}</button>)}</div><div className="catalog-meta"><span>{products.length} PRODUCTS</span><span>€20 — €100</span></div><div className="product-grid">{products.map(p=><ProductCard key={p.id} p={p} onClick={()=>onProduct(p)} favorite={favorites.includes(p.id)} onFavorite={()=>onFavorite(p.id)}/>)}</div>{products.length===0&&<div className="empty-state">NO PRODUCTS FOUND</div>}</div>}
function ProductCard({p,onClick,favorite,onFavorite}:{p:Product;onClick:()=>void;favorite:boolean;onFavorite:()=>void}){return <article className="product-card"><div className="product-media"><button onClick={onClick} className="media-button"><img src={p.images[0]} alt={p.name} loading="lazy" decoding="async"/></button><button onClick={e=>{e.stopPropagation();onFavorite()}} className="favorite-button" aria-label={favorite?'Remove from favorites':'Add to favorites'}><Heart size={15} fill={favorite?'currentColor':'none'} className={favorite?'favorite-on':''}/></button></div><button onClick={onClick} className="product-info"><div className="product-name">{p.name}</div><div className="product-price">€{p.price}</div></button></article>}
function ProductModal({product,onClose,onAdd}:{product:Product;onClose:()=>void;onAdd:(x:CartItem)=>void}){const[size,setSize]=useState(product.sizes[1]||product.sizes[0]),[color,setColor]=useState(product.colors[0].name);return <div className="modal-backdrop"><div className="sheet product-sheet"><div className="modal-media"><img src={product.images[0]} alt={product.name} loading="eager" decoding="async"/><button onClick={onClose} className="close-button" aria-label="Close"><X size={18}/></button></div><div className="sheet-content product-sheet-content"><div className="product-title-row"><div><div className="eyebrow red">{product.category}</div><h2>{product.name}</h2></div><div className="modal-price">€{product.price}</div></div><p className="description">{product.description}</p><div className="option-block"><div className="option-label">SIZE</div><div className="option-row">{product.sizes.map(s=><button key={s} onClick={()=>setSize(s)} className={size===s?'selected':''}>{s}</button>)}</div></div><div className="option-block"><div className="option-label">COLOR · {color.toUpperCase()}</div><div className="color-row">{product.colors.map(c=><button key={c.name} aria-label={c.name} onClick={()=>setColor(c.name)} style={{background:c.hex}} className={color===c.name?'color-selected':''}/>)}</div></div><div className="composition">COMPOSITION: {product.composition}</div><button onClick={()=>{onAdd({product,size,color,quantity:1});onClose()}} className="primary-red">ADD TO BAG · €{product.price}</button></div></div></div>}
function Cart({items,total,onClose,onChange,onCheckout}:{items:CartItem[];total:number;onClose:()=>void;onChange:(x:CartItem[])=>void;onCheckout:()=>void}){return <div className="modal-backdrop"><div className="sheet cart-sheet"><div className="sheet-title-row"><h2>YOUR BAG</h2><button onClick={onClose} className="close-button small" aria-label="Close"><X size={18}/></button></div>{items.length===0?<div className="empty-state large"><ShoppingBag size={42}/><p>YOUR BAG IS EMPTY</p><span>Add something from the collection.</span></div>:<><div>{items.map((i,idx)=><div key={`${i.product.id}-${i.size}-${i.color}`} className="cart-row"><img src={i.product.images[0]} alt="" loading="lazy"/><div className="cart-main"><div className="cart-name">{i.product.name}</div><div className="cart-meta">{i.color} · {i.size}</div><div className="cart-bottom"><div className="quantity"><button onClick={()=>onChange(items.map((x,j)=>j===idx?{...x,quantity:Math.max(1,x.quantity-1)}:x))}><Minus size={13}/></button><span>{i.quantity}</span><button onClick={()=>onChange(items.map((x,j)=>j===idx?{...x,quantity:x.quantity+1}:x))}><Plus size={13}/></button></div><b>€{i.product.price*i.quantity}</b></div></div></div>)}</div><div className="total-row"><span>TOTAL</span><strong>€{total}</strong></div><button onClick={onCheckout} className="primary-red">CHECKOUT</button></>}</div></div>}
function Checkout({total,onClose,onDone}:{total:number;onClose:()=>void;onDone:(x:{name:string;phone:string;delivery:string})=>void}){const[name,setName]=useState(''),[phone,setPhone]=useState(''),[delivery,setDelivery]=useState('SmartPost / Omniva');return <div className="checkout-screen"><div className="checkout-inner"><button onClick={onClose} className="back-button" aria-label="Back"><ChevronLeft size={20}/></button><p className="eyebrow red">ORDER</p><h1>CHECKOUT</h1><div className="form-stack"><Field label="NAME" value={name} onChange={setName} placeholder="Your name"/><Field label="PHONE" value={phone} onChange={setPhone} placeholder="+372 ..."/><div><label className="field-label">DELIVERY</label><select value={delivery} onChange={e=>setDelivery(e.target.value)}><option>SmartPost / Omniva</option><option>Courier</option><option>Pickup</option></select></div><div><label className="field-label">PAYMENT</label><div className="readonly-field">Cash on delivery</div></div></div><div className="checkout-total"><span>ORDER TOTAL</span><b>€{total}</b></div><button disabled={!name||phone.replace(/\D/g,'').length<7} onClick={()=>onDone({name,phone,delivery})} className="primary-red disabled-button">PLACE ORDER</button></div></div>}
function Field({label,value,onChange,placeholder}:{label:string;value:string;onChange:(x:string)=>void;placeholder:string}){return <div><label className="field-label">{label}</label><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>}
function Filters({size,color,maxPrice,colors,onClose,onApply}:{size:string;color:string;maxPrice:number;colors:string[];onClose:()=>void;onApply:(s:string,c:string,p:number)=>void}){const[s,setS]=useState(size),[c,setC]=useState(color),[p,setP]=useState(maxPrice);return <div className="modal-backdrop align-end"><div className="sheet filter-sheet"><div className="sheet-title-row"><h2>FILTERS</h2><button onClick={onClose} className="close-button small"><X size={18}/></button></div><div className="filter-group"><div className="option-label">SIZE</div><div className="option-row wrap">{['All',...sizes].map(x=><button key={x} onClick={()=>setS(x)} className={s===x?'selected':''}>{x}</button>)}</div></div><div className="filter-group"><div className="option-label">COLOR</div><div className="select-wrap"><select value={c} onChange={e=>setC(e.target.value)}>{colors.map(x=><option key={x}>{x}</option>)}</select><ChevronDown size={18}/></div></div><div className="filter-group"><div className="price-line"><span className="option-label">MAXIMUM PRICE</span><span>€{p}</span></div><input type="range" min="20" max="100" value={p} onChange={e=>setP(Number(e.target.value))}/></div><button onClick={()=>onApply(s,c,p)} className="primary-red">APPLY FILTERS</button></div></div>}
function Orders({orders}:{orders:Order[]}){return <div className="page-pad page-top"><p className="eyebrow red">ACCOUNT</p><h1 className="page-title">ORDERS</h1>{orders.length===0?<div className="empty-card"><PackageOpen size={34}/><h2>NO ORDERS YET</h2><p>Your order status will appear here after checkout.</p></div>:<div className="order-list">{orders.map(o=><div key={o.id} className="order-card"><div><b>ORDER #{o.id}</b><span>{o.items.length} items · €{o.total}</span></div><em>{o.status.toUpperCase()}</em></div>)}</div>}</div>}
function Profile(){return <div className="page-pad page-top"><p className="eyebrow red">YAROPLUGG</p><h1 className="page-title">PROFILE</h1><div className="profile-card"><img src="/logo.png" alt="YAROPLUGG"/><div className="field-label">TELEGRAM</div><div className="profile-title">Your account</div><p>Your Telegram identity can be connected here when backend auth is enabled.</p></div><div className="support-card">Store support</div></div>}
createRoot(document.getElementById('root')!).render(<App/>)
